### ISSUE TITLE
[FEATURE] Use videos instead of images

### ISSUE THREAD

**Issue by pamplemoussecache** [Accessible-Technology-in-Sign/PopSign#11]
**Is your feature request related to a problem? Please describe.**
Our APK is massive because we use a bunch of individual images

**Describe the solution you'd like**
I want us to use Unity's video players.

**Comment by pamplemoussecache** [comment]
@sreya101 @rajbsrivastava , where did we get to on this?

**Comment by rajandeepsingh13** [comment]
Fixed
