### ISSUE TITLE
Be able to put APK on Android

### ISSUE THREAD

**Issue by pamplemoussecache** [Accessible-Technology-in-Sign/PopSign#12]
Updates! Got this working. Required some substantial tweaking of my running environment, but I believe I now know everything that needs to be configured to be able to build APK on your computer.

Wrote a script to setup dev environment, currently wrapping that up, and will be adding it and instructions for running it into the repo's README shortly.

**Comment by pamplemoussecache** [comment]
Further progress is blocked on either #11 or #22 , as the size of the image files are prohibitively large, and are what is causing the build fail. It is possible to force it to build, but the resulting APK is non-playable.

**Comment by rajandeepsingh13** [comment]
APK builds work. Closing
