### ISSUE TITLE
Merge in code from Fall 2019 (Thad will provide the code)

### ISSUE THREAD

**Issue by pamplemoussecache** [Accessible-Technology-in-Sign/PopSign#22]
https://gtvault-my.sharepoint.com/:u:/g/personal/ts133_gatech_edu/EQeZMwn3O0tLuwFUf7pHjdoBtiQ7S8tOdv6UIyD8fb-nnA?e=vB6KZV

**Comment by rajandeepsingh13** [comment]
Stale. Closing.
