### ISSUE TITLE
[BUG] level 38 loads and plays incorrectly 

### ISSUE THREAD

**Issue by ljme** [Accessible-Technology-in-Sign/PopSign#48]
**Describe the bug**
Level 38 will load with the bubbles at the bottom of the screen. Your fired bubbles collect at the bottom of the screen until the entire level will drop all of the bubbles. Then, all bubbles are shot into nothing. 

The only way to advance beyond this level is to fire into there are no more balls remaining. I discovered this after many frustrating attempts to otherwise advance. 

**To Reproduce**
1. Go to level 38, accept the preview screen.
2. Start gameplay 

**Expected behavior**
Level loads similarly to all other levels. 

**Screenshots**
Video: https://photos.app.goo.gl/QjV8i8kcjXyJvws18

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Browser N/A, using app
 - Version 1.2.8 from April 18th 2023

**Additional context**
Reproduces 100% of the time. 
This also reproduces if the word choice is set to random, isolating this level setup as the issue.

**Comment by CDFalcon** [comment]
Thank you for the bug report! This has been patched and will be pushed with the next update. Please open up additional issues if you find similar glitched levels.

**Comment by ljme** [comment]
Please see bug #50 for the same problem on another level. Thanks!

**Comment by ljme** [comment]
Confirming this is resolved as of version 1.2.9. Thank you!
