### ISSUE TITLE
[BUG] level 108 loads and plays incorrectly 

### ISSUE THREAD

**Issue by ljme** [Accessible-Technology-in-Sign/PopSign#50]
This is the exact same problem as Level 38, bug #48 
I recommend setting up logic such that if there are no bubbles left on screen, the level is beaten. This will prevent bugs of this type from blocking progress. 

Level 108 will load with the bubbles at the bottom of the screen. Your fired bubbles collect at the bottom of the screen until the entire level will drop all of the bubbles. Then, all bubbles are shot into nothing.

The is no way to advance beyond this level, even if I fire until there are no more balls remaining. I'm completely stuck this time!!

To Reproduce
Go to level 108, accept the preview screen.
Start gameplay

Expected behavior
Level loads similarly to all other levels.

Smartphone (please complete the following information):

Device: Pixel 6a
OS: Android 13
Browser N/A, using app
Version 1.2.8 from April 18th 2023
Additional context
Reproduces 100% of the time.
This also reproduces if the word choice is set to random, isolating this level setup as the issue.

**Comment by ljme** [comment]
@CDFalcon would you be able to help with this level, too? It's completely blocking my progress in the game. Thanks!

**Comment by CDFalcon** [comment]
@ljme thanks for these reports! I'll patch these bugs and the last set you sent today and have the fix up later this afternoon. Expect the update to roll out sometime tomorrow :)

**Comment by ljme** [comment]
Thank you! Looking forward to it!

**Comment by ljme** [comment]
Confirming this is resolved as of version 1.2.9. Thank you!
